### ISSUE TITLE
ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by Blizzer92** [DevExpress/devextreme-angular-template#155]
Hello,

when I execute the command "npx -p devextreme-cli devextreme new angular-app xxx" I get the following error: 
Package installation failed: npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: xxx@0.0.0
npm ERR! Found: jasmine-core@3.6.0
npm ERR! node_modules / jasmine-core
npm ERR! dev jasmine-core @ "~ 3.6.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jasmine-core @ "> = 3.7.1" from karma-jasmine-html-reporter@1.6.0
npm ERR! node_modules / karma-jasmine-html-reporter
npm ERR! dev karma-jasmine-html-reporter @ "^ 1.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/xxx/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/xxx/.npm/_logs/2021-05-12T08_35_56_707Z-debug.log
Package install failed, see above.

That seems to be due to a new version of Jasmine.

**Comment by LexDX** [comment]
Hi @Blizzer92,

This issue can be reproducible with a standard Angular app and was fixed in the context of this Angular/CLI PR: https://github.com/angular/angular-cli/commit/b34ed5c4007f9ef08b370219081b4d23f9f24fb8

However, this PR is not included in the latest Angular release, so, to resolve the issue you can downgrade npm to v.6. Please check Angular/CLI issue for more info:
https://github.com/angular/angular-cli/issues/20719
