### ISSUE TITLE
Error generating production build

### ISSUE THREAD

**Issue by eliseurm** [DevExpress/devextreme-angular-template#159]
This version has been updated for Angular12 and is not being built for production.

`ng build --output-path = dist --configuration production`

Error:
```
✖ Index html generation failed.
undefined: 5: 144452: property missing ':'
```

There seems to be a problem with the way scss is going to be used going forward.

DevExtreme must configure its styles to meet this demand, in other projects I have the same problem.

**Comment by LexDX** [comment]
Hi @eliseurm,

This issue is related to the regression in the Angular library. Please check this GitHub issue for more information: https://github.com/angular/angular-cli/issues/20760
According to Alan's comment, the issue is caused by Angular-CLI. The Angular-CLI team will fix it in the scope of the following GitHub issue: https://github.com/reworkcss/css/issues/154.

In the meantime, you can use the inlineCritical option to resolve the issue:

```
"optimization": {
                "scripts": true,
                "styles": {
                  "minify": true,
                  "inlineCritical": false
                },
                "fonts": {
                  "inline": true
                }
              },
```
